Resources:
  Myinstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-09e67e426f25ce0d7
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref SSHSecurityGroup
        - !Ref ServerSecurityGroup

# Security Grupo 1 - SSHSecurityGroup
SSHSecurityGroup:
  Type: AWS::ECS::SecurityGroup
  Properties:
    GroupDescription: Enable SSH access via port 22
    SecurityGroupIngress:
    - CidrIp: 0.0.0.0/0
      FromPort: 22
      IpProtocol: tcp
      ToPort: 22


# Security Grupo 1 - ServerSecurityGroup
ServerSecurityGroup:
  Type: AWS::ECS::SecurityGroup
  Properties:
    GroupDescription: Enable http for anywhere
    SecurityGroupIngress:
    - IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      CidrIp: 0.0.0.0/0
